# Logistic Regression

In [1]:
# Logistic regression is used to estimate the probability that an instance belongs to a particular
# class (What is the probability that a given email is a spam ?) 
# Logistic regression uses the weighted sum of the inputs to compute a logit.
#The logit is passed through the sigmoid function to get the predicted probability.
#This probability is interpreted as the likelihood of the positive class (class 1).



### Decision Boundaries

In [46]:
# Building a classifier to detect the Iris virginica type based only on the petal width feature
import pandas as pd
import numpy as np
from sklearn import datasets
iris = datasets.load_iris() # Loading the iris dataset
list(iris.keys()) # This will give us all the name of columns
X = iris["data"][:,3:] # petal with 
# ,3: takes the colums 4 and onwards ad indexing of columns start form 0
y = (iris["target"] == 2).astype(int)
# this will change True and False into 0 and 1

In [49]:
y # One if verginica else 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [50]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X,y)

LogisticRegression()

In [59]:
log_reg.predict([[1.7]])

array([1])

## Evaluating the model

In [60]:
# 1. Make prediction
y_pred = log_reg.predict(X)

In [62]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [64]:
# 2. Accuracy Score : The most commong evaluation matric in accuracy, which measures the percentage
# correctly classified samples
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y,y_pred)

In [65]:
accuracy

0.96

In [73]:
# Models estimation probabilities for folowers with petal widths varying form 0 to 3 cm
X_new = np.linspace(0,3,1000).reshape(-1,1)
# This will genearte 1000 values in between 0 and 3 and then reshape that values into a column vector

In [91]:
plt.figure(figsize=(8, 6))  # Set the figure size for better readability
plt.plot(X_new, Y_pred[:, 1], "g-", label="Iris Virginica", linewidth=2, marker="o", markersize=4, markerfacecolor='green')  # Add green line for Iris Virginica
plt.plot(X_new, Y_pred[:, 0], "b--", label="Not Iris Virginica", linewidth=2, marker="x", markersize=4, markerfacecolor='blue')  # Add blue dashed line for Not Iris Virginica

# Add title and labels
plt.title("Predicted Probabilities for Iris Virginica vs. Not Iris Virginica", fontsize=14)
plt.xlabel("X values", fontsize=12)
plt.ylabel("Predicted Probability", fontsize=12)

# Add a legend
plt.legend(title="Class", loc="upper left")

# Add gridlines
plt.grid(True)

# Adjust the x-axis to avoid overlapping labels
plt.tight_layout()

# Show the plot
plt.show()

In [90]:
Y_pred

array([[9.99250016e-01, 7.49984089e-04],
       [9.99240201e-01, 7.59799387e-04],
       [9.99230257e-01, 7.69743043e-04],
       ...,
       [3.08374822e-03, 9.96916252e-01],
       [3.04400296e-03, 9.96955997e-01],
       [3.00476842e-03, 9.96995232e-01]])

In [92]:
# Here from the graph we can see that if the petal weidth value is greter then 1.6 then it 
# classifies it as Iris Virginica

In [93]:
# Just like the other linear models, Logistic Regression models can be regularized using
# l2 or l2 penalties. Scikit-Learn actually adds an l2 penalty by default.
#It is essentially the point (or line, in 2D) where the classifier's predicted probability for one
#class is equal to the predicted probability for the other class. For binary classification, this means
#that the decision boundary corresponds to where the model assigns a 50% probability to each class.



## Softmax Regression

In [ ]:
# The logistic Regression model can be generalized to support multiple classes directly, 
# without having to train and combine multiple binary classifiers. This is called as the 
# Softmax Regression or Multinomial Logistic Regression.